=== prolog/shadow-of-the-wyrm/data/maps/CustomMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:savage_lands:maps:1.0.0" targetNamespace="urn:savage_lands:maps:1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0.0">
<xs:element name="CustomMap">
	<xs:annotation><xs:documentation>XML element describing the custom maps that describe fixed locations within Savage Lands.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="tns:Dimensions"/>
			<xs:element name="MapType" type="tns:MapType"/>
			<!-- This is a string of tiles, rows x cols, that represents a particular tile type.  The map is created by
				 adding the corresponding tile to the corresponding row/col.  Whitespace is ignored, as is any
				 unrecognized character. -->
			<xs:element name="Tiles" type="xs:string"/>
			<xs:element name="PlayerStart" type="tns:Coord" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Dimensions">
	<xs:annotation><xs:documentation>The dimensions of the map.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Rows" type="xs:unsignedInt"/>
			<xs:element name="Columns" type="xs:unsignedInt"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<!-- Complex Types -->
<xs:complexType name="Coord">
	<xs:annotation><xs:documentation>A (y,x) coordinate.</xs:documentation></xs:annotation>
	<xs:sequence>
		<xs:element name="Row" type="xs:unsignedInt"/>
		<xs:element name="Col" type="xs:unsignedInt"/>
	</xs:sequence>
</xs:complexType>
<!-- Simple Types -->
<xs:simpleType name="MapType">
	<xs:annotation>
		<xs:documentation>
			See: world/include/MapTypes.hpp
			
			0 = World (do not use)
			1 = Overworld (forests, fields, villages, etc)
			2 = Underworld (caverns, dungeons, etc)
		</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:int">
		<xs:enumeration value="0"/>
		<xs:enumeration value="1"/>
		<xs:enumeration value="2"/>
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== prolog/shadow-of-the-wyrm/data/maps/Gnordvar.xml
<CustomMap id="gnordvar" xmlns="urn:savage_lands:maps:1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:savage_lands:maps:1.0.0 ./CustomMap.xsd">
	<Dimensions>
		<Rows>20</Rows>
		<Columns>80</Columns>
	</Dimensions>
	<MapType>1</MapType>
	<Tiles>
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	^^^^,,,,,,,,,,,,T,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^^^
	^^^^,,,T,,###########,,,,,,,T,,,,,,,,,,,,,,,,,,,,,,,,,,,#####,,,,,,,,,,&gt;,,,,^^^^
	^^^^,,,,,,#.........#,,,,,,,,,,,,,rrrrrrrrrr,,,,,,,,,,,,#...#,,,,,,,,,,r,,,,^^^^
	^^^^,,,,,,#.........#,,,,,,,,,T,,,rr,,,,,,,rrrrrrr,,,,,,##.##,T,,,,rrrrr,,,,^^^^
	rrrrr,,,,,#.........#,,,,,,,,,,,,,rr,,,,,,,,,,,,,rrrrrrrrrrrrrrrrrrr,,,,,,,,^^^^
	^^^^rrr,,,#####.#####,,T,,,,,,,,,,rr,,,T,,,,,,,,,,,,,,,,,,,,,,,,,,,,T,,,,,,,^^^^
	^^^^,,rrrrT,,,,,,,,,,,,,,,,,,,,,,,rr,,,,,,,,,,,,#####,,,,,,,,,,##.##,,,,,,,,^^^^
	^^^^,,,,,rrrrrrrrrrrrrrrrrrrrrrrrrrr,T,,,,,,T,,,#...#,,,,,,,,T,#...#,,,,,,,,^^^^
	^^^^,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,rr,,,,,,,,,,,,##.##,,,,,,,,,,#####,,,T,,,,^^^^
	^^^^,,,,,,,,,T,,,,,,,,,,,,,,,,,,,,rr,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^^^
	^^^^,##########,,,,,,,T,,,,,,,,,,,rr,,,,,T,,,,,,,,,,T,,,,,,,,,,,,,,,#######,^^^^
	^^^^,#........#,,,,,,,,,T,,,,,,,,,rr,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#.....#,^^^^
	^^^^,#.........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr......#,^^^^
	^^^^,#........#,,,,,,,,,,T,,,,T,,,,,##.##,,T,,,,,,,,,,,,,,,,,,,,,,,,#.....#,^^^^
	^^^^,##########,,,,,,T,,,,,,,,,,,,,,#...#,,,,,,,,,,,,,,,,,,,,,,T,,,,#######,^^^^
	^^^^,,,,T,,,,,,,,,,,,,,,,,,,,,,,,,,,#####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^^^
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	</Tiles>
	<PlayerStart>
		<Row>6</Row>
		<Col>0</Col>
	</PlayerStart>
	<InitialPlacements/>
	<Exits/>
</CustomMap>
