=== prolog/shadow-of-the-wyrm/data/SavageLands.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:savage_lands:1.0.0" targetNamespace="urn:savage_lands:1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0.0">
<!-- ELEMENTS -->
<xs:element name="SavageLands">
	<xs:annotation><xs:documentation>The configuration root node - contains all the races, classes, and game data.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="tns:Races"/>
			<xs:element ref="tns:Classes"/>
			<xs:element ref="tns:Tiles"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Races">
	<xs:annotation><xs:documentation>A list of races to be used at runtime within Savage Lands.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="tns:Race" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Classes">
	<xs:annotation><xs:documentation>A list of classes to be used at runtime within Savage Lands.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="tns:Class" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Tiles">
	<xs:annotation><xs:documentation>Contains information on the tile types</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="FieldTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="ScrubTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="WheatTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="CairnTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="TreeTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="DesertTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="RoadTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="RiverTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="SeaTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="ShoalsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="DungeonTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="RockTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="GraveTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="MarshTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="ReedsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="HillsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="MountainsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="BeachTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="BushTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="WeedsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="SpringsTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="ForestTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="UpStaircaseTile" type="tns:Tile" minOccurs="1"/>
			<xs:element name="DownStaircaseTile" type="tns:Tile" minOccurs="1"/>			
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Race">
	<xs:annotation><xs:documentation>A race within Savage Lands.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="UserPlayable" type="xs:boolean"/>
			<xs:element name="NameSID" type="xs:string"/>
   			<xs:element name="ShortDescriptionSID" type="xs:string"/>
			<xs:element name="DescriptionSID" type="xs:string"/>
			<xs:element name="DisplayAbbreviationSID" type="xs:string"/>
			<xs:element name="Size" type="tns:CreatureSizeType"/>
			<xs:element ref="tns:RaceInitialStatistics"/>
			<xs:element ref="tns:RaceInitialModifiers"/>
			<xs:element ref="tns:Resistances"/>
			<xs:element ref="tns:Skills"/>
			<xs:element  name="ExperienceMultiplier" type="tns:NonNegativeDecimal"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="ClassInitialStatistics">
<xs:annotation><xs:documentation>Classes control the initial value of Valour and Spirit.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Valour" type="tns:PrimaryStatistic"/>
			<xs:element name="Spirit" type="tns:PrimaryStatistic"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="RaceInitialStatistics">
<xs:annotation><xs:documentation>Races control the initial values of certain statistics.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Strength" type="tns:PrimaryStatistic"/>
			<xs:element name="Dexterity" type="tns:PrimaryStatistic"/>
			<xs:element name="Agility" type="tns:PrimaryStatistic"/>
			<xs:element name="Health" type="tns:PrimaryStatistic"/>
			<xs:element name="Intelligence" type="tns:PrimaryStatistic"/>
			<xs:element name="Willpower" type="tns:PrimaryStatistic"/>
			<xs:element name="Charisma" type="tns:PrimaryStatistic"/>
			<xs:element name="Speed" type="tns:Statistic"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="ClassInitialModifiers">
<xs:annotation><xs:documentation>Races have a set of modifiers for certain statistics.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="StrengthModifier" type="tns:StatisticModifier"/>
			<xs:element name="DexterityModifier" type="tns:StatisticModifier"/>
			<xs:element name="AgilityModifier" type="tns:StatisticModifier"/>
			<xs:element name="HealthModifier" type="tns:StatisticModifier"/>
			<xs:element name="IntelligenceModifier" type="tns:StatisticModifier"/>
			<xs:element name="WillpowerModifier" type="tns:StatisticModifier"/>
			<xs:element name="CharismaModifier" type="tns:StatisticModifier"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="RaceInitialModifiers">
<xs:annotation><xs:documentation>Races have a set of modifiers for certain statistics.</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="ValourModifier" type="tns:StatisticModifier"/>
			<xs:element name="SpiritModifier" type="tns:StatisticModifier"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Class">
	<xs:annotation>
		<xs:documentation>A creature Class.</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="UserPlayable" type="xs:boolean"/>
			<xs:element name="NameSID" type="xs:string"/>
			<xs:element name="DescriptionSID" type="xs:string"/>
			<xs:element name="DisplayAbbreviationSID" type="xs:string"/>
			
<xs:element ref="tns:ClassInitialStatistics"/>
			
<xs:element ref="tns:ClassInitialModifiers"/>
			<xs:element ref="tns:Resistances"/>
			<xs:element ref="tns:Skills"/>
			<xs:element  name="ExperienceMultiplier" type="tns:NonNegativeDecimal"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Resistances">
<xs:annotation><xs:documentation>Each resistance is either positive (resistance) or negative (vulnerability), and is a delta subtracted from a base value of 1.  The final resistance is a damage multiplier, so any value greater than 1 inflicts more damage, and any value less than 1 inflicts less damage (in extreme cases, values can be negative, which heal)</xs:documentation></xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Slash" type="xs:float"/>
			<xs:element name="Pierce" type="xs:float"/>
			<xs:element name="Pound" type="xs:float"/>
			<xs:element name="Heat" type="xs:float"/>
			<xs:element name="Cold" type="xs:float"/>
			<xs:element name="Acid" type="xs:float"/>
			<xs:element name="Poison" type="xs:float"/>
			<xs:element name="Holy" type="xs:float"/>
			<xs:element name="Shadow" type="xs:float"/>
			<xs:element name="Arcane" type="xs:float"/>
			<xs:element name="Mental" type="xs:float"/>
			<xs:element name="Sonic" type="xs:float"/>
			<xs:element name="Radiant" type="xs:float"/>
			<xs:element name="Lightning" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="GeneralSkills">
	<xs:annotation>
		<xs:documentation>General skills (not weapon or magic)</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Archery" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Awareness" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Bargaining" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Beastmastery" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="BlindFighting" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Boating" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Bowyer" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Brewing" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Cantrips" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Carrying" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Combat" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Crafting" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="DesertLore" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Detection" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="DisarmTraps" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="DualWield" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Dungeoneering" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Escape" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Fishing" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Fletchery" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Foraging" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="ForestLore" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Herbalism" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Hiding" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Hunting" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Intimidation" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Jeweler" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Jumping" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Leadership" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Literacy" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Lore" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Magic" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="MarshLore" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Medicine" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="MountainLore" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Mountaineering" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Music" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="NightSight" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Oceanography" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Papercraft" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Religion" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Scribing" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Skinning" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Smithing" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Spelunking" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Stealth" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Swimming" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Tanning" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Thievery" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Weaving" type="tns:PercentageStatistic" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="WeaponSkills">
	<xs:annotation>
		<xs:documentation>Melee weapon skills such as clubs, swords, etc.</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Axes" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="ShortBlades" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="LongBlades" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Bludgeons" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Daggers" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="RodsAndStaves" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Spears" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Unarmed" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Whips" type="tns:PercentageStatistic" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="RangedWeaponSkills">
	<xs:annotation>
		<xs:documentation>Ranged weapon skills such as bows, slings, etc.</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Axes" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Blades" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Bludgeons" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Bows" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Crossbows" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Daggers" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Rocks" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Slings" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Spears" type="tns:PercentageStatistic" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="MagicSkills">
	<xs:annotation>
		<xs:documentation>Magic skills</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Arcane" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Divine" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Mystic" type="tns:PercentageStatistic" minOccurs="0"/>
			<xs:element name="Primordial" type="tns:PercentageStatistic" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Skills">
	<xs:annotation>
		<xs:documentation>The general, melee, ranged, and magic skills available.</xs:documentation>
	</xs:annotation>
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="tns:GeneralSkills"  minOccurs="0"/>
		<xs:element ref="tns:WeaponSkills" minOccurs="0"/>
		<xs:element ref="tns:RangedWeaponSkills" minOccurs="0"/>
		<xs:element ref="tns:MagicSkills" minOccurs="0"/>		
	</xs:sequence>
	</xs:complexType>
</xs:element>
<!-- COMPLEX TYPES -->
<xs:complexType name="Tile">
	<xs:annotation><xs:documentation>Contains information about a particular tile type</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="Text" type="tns:TextDetails" minOccurs="1"/>
		</xs:sequence>
</xs:complexType>
<xs:complexType name="TextDetails">
	<xs:annotation>
		<xs:documentation>Contains information about a particular tile type</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="Symbol" type="xs:string" minOccurs="1"/>
		<xs:element name="Colour" type="tns:ColourType" minOccurs="1"/>
	</xs:sequence>
</xs:complexType>
<!-- SIMPLE TYPES -->
<xs:simpleType name="CreatureSizeType">
	<xs:annotation>
		<xs:documentation>An enumeration describing creature size.
					0 = Tiny
					1 = Small
					2 = Medium
					3 = Large
					4 = Huge
					5 = Behemoth
		</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="0"/>
		<xs:maxExclusive value="5"/>		
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="Statistic">
	<xs:annotation>
		<xs:documentation>General statistics (like HP, AP, etc) can be any integer value.</xs:documentation>
	</xs:annotation>
	<xs:union memberTypes="xs:integer"/>
</xs:simpleType>
<xs:simpleType name="StatisticModifier">
	<xs:annotation>
		<xs:documentation>A modifier for a statistic (Str, HP, etc) can be any integer value.</xs:documentation>
	</xs:annotation>
	<xs:union memberTypes="xs:integer"/>
</xs:simpleType>
<xs:simpleType name="PercentageStatistic">
	<xs:annotation>
		<xs:documentation>Percentage statistics, for things like Skills</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="0"/>
		<xs:maxExclusive value="100"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="PrimaryStatistic">
	<xs:annotation>
		<xs:documentation>Primary statistics (such as Strength, Intelligence, etc) can range between 1 and 99.</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="1"/>
		<xs:maxExclusive value="99"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ColourType">
	<xs:annotation>
		<xs:documentation>
			The colour, for text-based terminals.  See jrcpp/include/Colour.hpp.
			0 = Black
			1 = Red
			2 = Green
			3 = Yellow
			4 = Blue
			5 = Magenta
			6 = Cyan
			7 = White
			8 = Bold Black
			9 = Bold Red
			10 = Bold Green
			11 = Bold Yellow
			12 = Bold Blue
			13 = Bold Magenta
			14 = Bold Cyan
			15 = Bold White
		</xs:documentation>
	</xs:annotation>

	<xs:restriction base="xs:int">

		<xs:minInclusive value="0"/>

		<xs:maxExclusive value="15"/>

	</xs:restriction>

</xs:simpleType>
<xs:simpleType name="NonNegativeDecimal">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== prolog/shadow-of-the-wyrm/data/SavageLands.xml
<SavageLands xmlns="urn:savage_lands:1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:savage_lands:1.0.0 SavageLands.xsd">
	<Races>
		<Race id="1_human">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_1_NAME</NameSID>
			<DescriptionSID>RACE_1_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_1_ABRV</DisplayAbbreviationSID>
			<Size>2</Size>
			<RaceInitialStatistics>
				<Strength>11</Strength>
				<Dexterity>10</Dexterity>
				<Agility>10</Agility>
				<Health>11</Health>
				<Intelligence>10</Intelligence>
				<Willpower>10</Willpower>
				<Charisma>10</Charisma>
				<Speed>50</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>5</ValourModifier>
				<SpiritModifier>5</SpiritModifier>
			</RaceInitialModifiers>
			<Resistances>
				<Slash>0.0</Slash>
				<Pierce>0.0</Pierce>
				<Pound>0.0</Pound>
				<Heat>0.0</Heat>
				<Cold>0.0</Cold>
				<Acid>0.0</Acid>
				<Poison>0.0</Poison>
				<Holy>0.0</Holy>
				<Shadow>0.0</Shadow>
				<Arcane>0.0</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.0</Radiant>
				<Lightning>0.0</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Boating>10</Boating>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<Fishing>15</Fishing>
					<Foraging>15</Foraging>
					<Hiding>10</Hiding>
					<Swimming>15</Swimming>
				</GeneralSkills>
				<WeaponSkills>
					<ShortBlades>5</ShortBlades>
					<Bludgeons>5</Bludgeons>
					<Daggers>5</Daggers>
					<Spears>5</Spears>
				</WeaponSkills>
				<RangedWeaponSkills>
					<Rocks>5</Rocks>
					<Slings>5</Slings>
				</RangedWeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.0</ExperienceMultiplier>		
		</Race>
		<Race id="2_woodelf">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_2_NAME</NameSID>
			<DescriptionSID>RACE_2_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_2_ABRV</DisplayAbbreviationSID>
			<Size>2</Size>
			<RaceInitialStatistics>
				<Strength>8</Strength>
				<Dexterity>14</Dexterity>
				<Agility>15</Agility>
				<Health>7</Health>
				<Intelligence>13</Intelligence>
				<Willpower>10</Willpower>
				<Charisma>10</Charisma>
				<Speed>47</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>4</ValourModifier>
				<SpiritModifier>6</SpiritModifier>
			</RaceInitialModifiers>
			<Resistances>
				<Slash>0.0</Slash>
				<Pierce>0.0</Pierce>
				<Pound>0.0</Pound>
				<Heat>-0.05</Heat>
				<Cold>0.0</Cold>
				<Acid>0.0</Acid>
				<Poison>0.0</Poison>
				<Holy>0.0</Holy>
				<Shadow>0.0</Shadow>
				<Arcane>0.10</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.0</Radiant>
				<Lightning>0.0</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Archery>15</Archery>
					<Awareness>15</Awareness>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<ForestLore>20</ForestLore>
					<Herbalism>10</Herbalism>
					<NightSight>15</NightSight>
					<Swimming>15</Swimming>
				</GeneralSkills>
				<WeaponSkills>
					<LongBlades>7</LongBlades>
				</WeaponSkills>
				<RangedWeaponSkills>
					<Bows>7</Bows>
				</RangedWeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.05</ExperienceMultiplier>		
		</Race>
		<Race id="3_mountainelf">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_3_NAME</NameSID>
			<DescriptionSID>RACE_3_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_3_ABRV</DisplayAbbreviationSID>
			<Size>2</Size>
			<RaceInitialStatistics>
				<Strength>9</Strength>
				<Dexterity>13</Dexterity>
				<Agility>12</Agility>
				<Health>11</Health>
				<Intelligence>12</Intelligence>
				<Willpower>11</Willpower>
				<Charisma>9</Charisma>
				<Speed>50</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>6</ValourModifier>
				<SpiritModifier>4</SpiritModifier>
			</RaceInitialModifiers>	
			<Resistances>
				<Slash>0.0</Slash>
				<Pierce>0.0</Pierce>
				<Pound>0.0</Pound>
				<Heat>0.0</Heat>
				<Cold>0.25</Cold>
				<Acid>-0.10</Acid>
				<Poison>-0.15</Poison>
				<Holy>0.0</Holy>
				<Shadow>0.0</Shadow>
				<Arcane>0.0</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.0</Radiant>
				<Lightning>0.0</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Archery>15</Archery>
					<Awareness>15</Awareness>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<MountainLore>20</MountainLore>
					<Mountaineering>20</Mountaineering>
					<NightSight>10</NightSight>
					<Spelunking>10</Spelunking>
					<Swimming>15</Swimming>
				</GeneralSkills>
				<WeaponSkills>
					<Bludgeons>7</Bludgeons>
				</WeaponSkills>
				<RangedWeaponSkills>
					<Rocks>5</Rocks>
					<Slings>7</Slings>
				</RangedWeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.02</ExperienceMultiplier>
		</Race>
		<Race id="4_marshelf">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_4_NAME</NameSID>
			<DescriptionSID>RACE_4_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_4_ABRV</DisplayAbbreviationSID>
			<Size>2</Size>
			<RaceInitialStatistics>
				<Strength>7</Strength>
				<Dexterity>11</Dexterity>
				<Agility>12</Agility>
				<Health>8</Health>
				<Intelligence>14</Intelligence>
				<Willpower>14</Willpower>
				<Charisma>7</Charisma>
				<Speed>50</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>2</ValourModifier>
				<SpiritModifier>8</SpiritModifier>
			</RaceInitialModifiers>	
			<Resistances>
				<Slash>-0.05</Slash>
				<Pierce>-0.05</Pierce>
				<Pound>0.0</Pound>
				<Heat>0.0</Heat>
				<Cold>-0.15</Cold>
				<Acid>0.0</Acid>
				<Poison>0.20</Poison>
				<Holy>0.0</Holy>
				<Shadow>0.0</Shadow>
				<Arcane>0.20</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.15</Radiant>
				<Lightning>0.0</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Awareness>15</Awareness>
					<Boating>15</Boating>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<MarshLore>20</MarshLore>
					<NightSight>10</NightSight>
					<Swimming>15</Swimming>
				</GeneralSkills>
				<WeaponSkills>
					<Spears>7</Spears>
				</WeaponSkills>
				<RangedWeaponSkills>
					<Spears>7</Spears>
				</RangedWeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.08</ExperienceMultiplier>
		</Race>
		<Race id="5_pixie">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_5_NAME</NameSID>
			<DescriptionSID>RACE_5_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_5_ABRV</DisplayAbbreviationSID>
			<Size>0</Size>
			<RaceInitialStatistics>
				<Strength>5</Strength>
				<Dexterity>14</Dexterity>
				<Agility>17</Agility>
				<Health>6</Health>
				<Intelligence>17</Intelligence>
				<Willpower>12</Willpower>
				<Charisma>10</Charisma>
				<Speed>45</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>0</ValourModifier>
				<SpiritModifier>10</SpiritModifier>
			</RaceInitialModifiers>	
			<Resistances>
				<Slash>-0.05</Slash>
				<Pierce>-0.05</Pierce>
				<Pound>-0.05</Pound>
				<Heat>0.05</Heat>
				<Cold>0.05</Cold>
				<Acid>-0.15</Acid>
				<Poison>-0.10</Poison>
				<Holy>0.10</Holy>
				<Shadow>0.10</Shadow>
				<Arcane>0.25</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.20</Radiant>
				<Lightning>0.10</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Awareness>15</Awareness>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<Escape>20</Escape>
					<ForestLore>25</ForestLore>
					<Herbalism>10</Herbalism>
					<Magic>15</Magic>
					<NightSight>15</NightSight>
					<Stealth>15</Stealth>
				</GeneralSkills>
				<WeaponSkills>
					<Daggers>5</Daggers>
				</WeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.13</ExperienceMultiplier>
		</Race>
		<Race id="6_dwarf">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_6_NAME</NameSID>
			<DescriptionSID>RACE_6_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_6_ABRV</DisplayAbbreviationSID>			
			<Size>1</Size>
			<RaceInitialStatistics>
				<Strength>14</Strength>
				<Dexterity>9</Dexterity>
				<Agility>8</Agility>
				<Health>13</Health>
				<Intelligence>9</Intelligence>
				<Willpower>12</Willpower>
				<Charisma>8</Charisma>
				<Speed>50</Speed>
			</RaceInitialStatistics>
			<RaceInitialModifiers>
				<ValourModifier>8</ValourModifier>
				<SpiritModifier>2</SpiritModifier>
			</RaceInitialModifiers>	
			<Resistances>
				<Slash>0.0</Slash>
				<Pierce>0.0</Pierce>
				<Pound>0.05</Pound>
				<Heat>0.1</Heat>
				<Cold>0.0</Cold>
				<Acid>0.0</Acid>
				<Poison>0.0</Poison>
				<Holy>0.0</Holy>
				<Shadow>0.0</Shadow>
				<Arcane>-0.10</Arcane>
				<Mental>0.0</Mental>
				<Sonic>0.0</Sonic>
				<Radiant>0.0</Radiant>
				<Lightning>0.0</Lightning>
			</Resistances>
			<Skills>
				<GeneralSkills>
					<Carrying>10</Carrying>
					<Detection>10</Detection>
					<DisarmTraps>10</DisarmTraps>
					<MountainLore>20</MountainLore>
					<NightSight>15</NightSight>
					<Smithing>20</Smithing>
					<Spelunking>20</Spelunking>
				</GeneralSkills>
				<WeaponSkills>
					<Axes>7</Axes>
					<Bludgeons>7</Bludgeons>
				</WeaponSkills>
				<RangedWeaponSkills>
					<Crossbows>5</Crossbows>
				</RangedWeaponSkills>
			</Skills>
			<ExperienceMultiplier>1.04</ExperienceMultiplier>
		</Race>
		<Race id="7_goblin">
			<UserPlayable>1</UserPlayable>
			<NameSID>RACE_7_NAME</NameSID>
			<DescriptionSID>RACE_7_DESC</DescriptionSID>
			<DisplayAbbreviationSID>RACE_7_ABRV</DisplayAbbreviationSID>
			<Size>1</Size>
			<RaceInitialStatistics>
				<Strength>9</Strength>
