=== prolog/shadow-of-the-wyrm/data/maps/world/WorldMapAreas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:savage_lands:maps:world_map:1.0.0" targetNamespace="urn:savage_lands:maps:world_map:1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0.0">
	<!-- Elements -->
	<xs:element name="WorldMap" type="tns:WorldMapType"/>
	<!-- Complex Types -->
	<xs:complexType name="WorldMapType">
		<xs:sequence>
			<xs:element name="Areas" type="tns:AreasType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AreasType">
		<xs:sequence>
			<xs:element name="Area" type="tns:AreaType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AreaType">
		<xs:sequence>
			<xs:element name="Row" type="tns:RowType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Script" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="RowType">
		<xs:simpleContent>
		  <xs:extension base="xs:string">
				<xs:attribute name="y" type="xs:integer"/>
				<xs:attribute name="x" type="xs:integer"/>
		  </xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== prolog/shadow-of-the-wyrm/data/maps/world/WorldMapAreas.xml
<WorldMap xmlns="urn:savage_lands:maps:world_map:1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:savage_lands:maps:world_map:1.0.0 ./WorldMapAreas.xsd">
	<Areas>
		<Area id="little_island">
			<Row y="95" x="94">~~~~~~</Row>
			<Row y="96" x="94">~KF~~~</Row>
			<Row y="97" x="94">~~vgO~</Row>
			<Row y="98" x="94">~~~~d~</Row>
			<Row y="99" x="94">~~~~~~</Row>
			<Script>areas/little_island.lua</Script>
		</Area>
		<Area id="infinite_dungeon">
			<Row y="87" x="97">~~~</Row>
			<Row y="88" x="97">~F~</Row>
			<Row y="89" x="97">FdF</Row>
			<Row y="90" x="97">~F~</Row>
			<Row y="91" x="97">~~~</Row>
			<Script>areas/infinite_dungeon.lua</Script>
		</Area>
	</Areas>
</WorldMap>
